# Don't print a new line at the start of the prompt
add_newline = false
 
[character]																	# The name of the module we are configuring is "character"
success_symbol = "[λ :: ](bold fg:134)"
error_symbol = "[λ ❯ ](bold red) "
 
# ------------------------------------------
# All disabled configs go here
[battery]
disabled = true
 
[cmd_duration]
disabled = true
 
[julia]
disabled = true
 
[kotlin]
disabled = true
 
[kubernetes]
disabled = true
 
[ocaml]
disabled = true
 
[openstack]
disabled = true
